### ISSUE TITLE
Issue in renderer.

### ISSUE THREAD

**Issue by floppycracken** [CyberAgentAILab/OpenCOLE#17]
When I run the code for the renderer I get this error: ValueError: 'textElement' is not in list 
The error occurs in the file crello.py file in line 137.
The same code used to work a few months back, I wanted to know if something has been changed in the crello dataset since then which may be cause of the error.
Thank You

**Comment by naoto0804** [comment]
Thank you for reporting the errors!
[Crello](https://huggingface.co/datasets/cyberagent/crello) dataset has been updated to v5.0.0, but this codebase assumes v4.0.0. Please load the dataset as follows:

```
import datasets
dataset = datasets.load_dataset("cyberagent/crello", revision="4.0.0")
```
I will force the codebase to use v4.0.0. in the near future.

**Comment by floppycracken** [comment]
Thank you for your quick response, this worked.
Also, I had another question, can the text be rendered with a transparent canvas? I want a separate text layer on its own.

**Comment by naoto0804** [comment]
Yes, you can disable [this line](https://github.com/CyberAgentAILab/OpenCOLE/blob/main/src/opencole/renderer/renderer.py#L59) so that the layers are rendered on blank canvas, and render as png instead of jpeg [here](https://github.com/CyberAgentAILab/OpenCOLE/blob/main/src/opencole/renderer/renderer.py#L101)
